name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greet
        run: echo "Hello Hello"
      - name: Print Bye
        run: echo "Done - Bye!"
